USE ticketing_db;

DROP TABLE IF EXISTS `feCountry`;
CREATE TABLE `feCountry` (
  `CountryISO2` varchar(2) NOT NULL,
  `CountryLangCode` varchar(5) NULL,
  `CountryISO3` varchar(3) NULL,
  `CountryDE` varchar(200) NULL,
  `CountryEN` varchar(200) NULL,
  `CountryCapital` varchar(200) NULL,
  `CountryIOC` varchar(3) NULL,
  `CountryContinent` varchar(100) NULL,
  `CountryDomain` varchar(6) NULL,
  `CountryCurrancy` varchar(5) NULL,
  `CountryAreaCode` varchar(10) NULL,
  `CountryEU` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `CountryLocale` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`CountryISO2`)
)
ENGINE = MyISAM DEFAULT CHARSET=UTF8MB4;

INSERT INTO feCountry VALUES ('AF',null,'AFG','Afghanistan','Afghanistan','Kabul','AFG','Asien','.af','AFN','+93',0,0)
,('EG',null,'EGY','Ägypten','Egypt','Kairo','EGY','Afrika','.eg','EGP','+20',0,0)
,('AX',null,'ALA','Aland','Åland Islands','Mariehamn',null,'Europa','.ax','EUR','+35818',0,0)
,('AL',null,'ALB','Albanien','Albania','Tirana','ALB','Europa','.al','ALL','+355',0,0)
,('DZ',null,'DZA','Algerien','Algeria','Algier','ALG','Afrika','.dz','DZD','+213',0,0)
,('AS',null,'ASM','Amerikanisch-Samoa','American Samoa','Pago-Pago',null,'Australien','.as','USD','+1684',0,0)
,('VI',null,'VIR','Amerikanische Jungferninseln','Virgin Islands, U.s.','Charlotte Amalie',null,'Südamerika','.vi','USD','+1340',0,0)
,('AD',null,'AND','Andorra','Andorra','Andorra la Vella','AND','Europa','.ad','EUR','+376',0,0)
,('AO',null,'AGO','Angola','Angola','Luanda','ANG','Afrika','.ao','AOA','+244',0,0)
,('AI',null,'AIA','Anguilla','Anguilla','The Valley',null,'Nordamerika','.ai','XCD','+1264',0,0)
,('AQ',null,'ATA','Antarktis','Antarctica','Juneau',null,'Antarktika','.aq',null,'+672',0,0)
,('AG',null,'ATG','Antigua und Barbuda','Antigua And Barbuda','Saint John\'s','ANT','Nordamerika','.ag','XCD','+1268',0,0)
,('GQ',null,'GNQ','Äquatorialguinea, Republik','Equatorial Guinea','Malabo','GEQ','Afrika','.gq','XAF','+240',0,0)
,('AR',null,'ARG','Argentinien','Argentina','Buenos Aires','ARG','Südamerika','.ar','ARS','+54',0,0)
,('AM',null,'ARM','Armenien','Armenia','Eriwan','ARM','Asien','.am','AMD','+374',0,0)
,('AW',null,'ABW','Aruba','Aruba','Oranjestad','ARU','Nordamerika','.aw','ANG','+297',0,0)
,('AC',null,'ASC','Ascension',null,'-/-',null,'Afrika','.ac',null,'+247',0,0)
,('AZ',null,'AZE','Aserbaidschan','Azerbaijan','Baku','AZE','Asien','.az','AZN','+994',0,0)
,('ET',null,'ETH','Äthiopien','Ethiopia','Addis Abeba','ETH','Afrika','.et','ETB','+251',0,0)
,('AU',null,'AUS','Australien','Australia','Canberra','AUS','Australien','.au','AUD','+61',0,0)
,('BS',null,'BHS','Bahamas','Bahamas','Nassau','BAH','Nordamerika','.bs','BSD','+1242',0,0)
,('BH',null,'BHR','Bahrain','Bahrain','Manama','BRN','Asien','.bh','BHD','+973',0,0)
,('BD',null,'BGD','Bangladesch','Bangladesh','Dhaka','BAN','Asien','.bd','BDT','+880',0,0)
,('BB',null,'BRB','Barbados','Barbados','Bridgetown','BAR','Nordamerika','.bb','BBD','+1246',0,0)
,('BE',null,'BEL','Belgien','Belgium','Brüssel','BEL','Europa','.be','EUR','+32',1,0)
,('BZ',null,'BLZ','Belize','Belize','Belmopan','BLZ','Nordamerika','.bz','BZD','+51',0,0)
,('BJ',null,'BEN','Benin','Benin','Porto Novo','BEN','Afrika','.bj','XOF','+229',0,0)
,('BM',null,'BMU','Bermuda','Bermuda','Hamilton','BER','Nordamerika','.bm','BMD','+1441',0,0)
,('BT',null,'BTN','Bhutan','Bhutan','Thimphu','BHU','Asien','.bt','BTN','+975',0,0)
,('BO',null,'BOL','Bolivien','Bolivia','Sucre','BOL','Südamerika','.bo','BOB','+591',0,0)
,('BA',null,'BIH','Bosnien und Herzegowina','Bosnia And Herzegovina','Sarajevo','BIH','Europa','.ba','BAM','+387',0,0)
,('BW',null,'BWA','Botswana','Botswana','Gaborone','BOT','Afrika','.bw','BWP','+267',0,0)
,('BV',null,'BVT','Bouvetinsel','Bouvet Island','(Forschungsinsel)',null,'Antarktika','.bv','NOK',null,0,0)
,('BR',null,'BRA','Brasilien','Brazil','Brasília','BRA','Südamerika','.br','BRL','+55',0,0)
,('VG',null,'VGB','Britische Jungferninseln','Virgin Islands, British','Road Town','ISB','Nordamerika','.vg','USD','+1284',0,0)
,('IO',null,'IOT','Britisches Territorium im Indischen Ozean','British Indian Ocean Territory','-/-',null,'Asien','.io','USD',null,0,0)
,('BN',null,'BRN','Brunei','Brunei Darussalam','Bandar Seri Begawan','BRU','Asien','.bn','BND','+673',0,0)
,('BG',null,'BGR','Bulgarien','Bulgaria','Sofia','BUL','Europa','.bg','BGN','+359',1,0)
,('BF',null,'BFA','Burkina Faso','Burkina Faso','Ouagadougou','BUR','Afrika','.bf','XOF','+226',0,0)
,('BI',null,'BDI','Burundi','Burundi','Bujumbura','BDI','Afrika','.bi','BIF','+257',0,0)
,('CL',null,'CHL','Chile','Chile','Santiago','CHI','Südamerika','.cl','CLP','+56',0,0)
,('CN',null,'CHN','China, Volksrepublik','China','Peking (Beijing)','CHN','Asien','.cn','CNY','+86',0,0)
,('CK',null,'COK','Cookinseln','Cook Islands','Avarua','COK','Australien','.ck','NZD','+682',0,0)
,('CR',null,'CRI','Costa Rica','Costa Rica','San José','CRC','Nordamerika','.cr','CRC','+56',0,0)
,('CI',null,'CIV','Cote d´Ivoire','CÔte D\'ivoire','Yamoussoukro','CIV','Afrika','.ci','XOF','+225',0,0)
,('DK',null,'DNK','Dänemark','Denmark','Kopenhagen','DEN','Europa','.dk','DKK','+45',1,0)
,('DE','de-de','DEU','Deutschland','Germany','Berlin','GER','Europa','.de','EUR','+49',1,0)
,('SH',null,'SHN','St. Helena und Nebengebiete','Saint Helena','Jamestown',null,'Afrika','.sh','SHP','+290',0,0)
,('DG',null,'DGA','Diego Garcia',null,null,null,'Afrika',null,null,'+246',0,0)
,('DM',null,'DMA','Dominica','Dominica','Roseau',null,'Nordamerika','.dm','XCD','+1767',0,0)
,('DO',null,'DOM','Dominikanische Republik','Dominican Republic','Santo Domingo','DOM','Südamerika','.do','DOP','+1809',0,0)
,('DJ',null,'DJI','Dschibuti','Djibouti','Dschibuti','DJI','Afrika','dj','DJF','+253',0,0)
,('EC',null,'ECU','Ecuador','Ecuador','Quito','ECU','Südamerika','.ec','USD','+593',0,0)
,('SV',null,'SLV','El Salvador','El Salvador','San Salvador','ESA','Nordamerika','.sv','SVC','+53',0,0)
,('ER',null,'ERI','Eritrea','Eritrea','Asmara (Asmera)','ERI','Afrika','.er','ERN','+291',0,0)
,('EE',null,'EST','Estland','Estonia','Tallinn (Reval)','EST','Europa','.ee','EEK','+372',1,0)
,('EU',null,'-/-','Europäische Union',null,'Brüssel','-/-','Europa','.eu',null,'+3883',0,0)
,('FK',null,'FLK','Falklandinseln','Falkland Islands (malvinas)','Port Stanley',null,'Afrika','.fk','FLP','+500',0,0)
,('FO',null,'FRO','Färöer','Faroe Islands','Tórshavn','FRO','Europa','.fo','DKK','+298',0,0)
,('FJ',null,'FJI','Fidschi','Fiji','Suva','FJI','Australien','.fj','FJD','+679',0,0)
,('FI',null,'FIN','Finnland','Finland','Helsinki','FIN','Europa','.fi','EUR','+358',1,0)
,('FR',null,'FRA','Frankreich','France','Paris','FRA','Europa','.fr','EUR','+33',1,0)
,('GF',null,'GUF','Französisch-Guayana','French Guiana','Cayenne',null,'Südamerika','.gf','EUR','+594',0,0)
,('PF',null,'PYF','Französisch-Polynesien','French Polynesia','Papeete',null,'Australien','.pf','XPF','+689',0,0)
,('TF',null,'ATF','Französische Süd- und Antarktisgebiete','French Southern Territories','Port-aux-Français',null,null,'.tf','EUR',null,0,0)
,('GA',null,'GAB','Gabun','Gabon','Libreville','GAB','Afrika','.ga','XAF','+241',0,0)
,('GM',null,'GMB','Gambia','Gambia','Banjul','GAM','Afrika','.gm','GMD','+220',0,0)
,('GE',null,'GEO','Georgien','Georgia','Tiflis','GEO','Europa','.ge','GEL','+995',0,0)
,('GH',null,'GHA','Ghana, Republik','Ghana','Accra','GHA','Afrika','.gh','GHC','+233',0,0)
,('GI',null,'GIB','Gibraltar','Gibraltar','Gibraltar (Stadt)',null,'Afrika','.gi','GIP','+350',0,0)
,('GD',null,'GRD','Grenada','Grenada','St. George\'s','GRN','Nordamerika','.gd','XCD','+1473',0,0)
,('GR',null,'GRC','Griechenland','Greece','Athen','GRE','Europa','.gr','EUR','+30',1,0)
,('GL',null,'GRL','Grönland','Greenland','Nuuk',null,'Nordamerika','.gl','DKK','+299',0,0)
,('GP',null,'GLP','Guadeloupe',null,'Basse-Terre',null,'Nordamerika','.gp','EUR','+590',0,0)
,('GU',null,'GUM','Guam','Guam','Hagåtña','GUM','Asien','.gu','USD','+1671',0,0)
,('GT',null,'GTM','Guatemala','Guatemala','Guatemala-Stadt','GUA','Nordamerika','.gt','GTQ','+52',0,0)
,('GG',null,'GGY','Guernsey, Vogtei','Guernsey','St. Peter Port',null,'Europa','.gg','GGP','+44',0,0)
,('GN',null,'GIN','Guinea, Republik','Guinea','Conakry','GUI','Afrika','.gn','GNF','+224',0,0)
,('GW',null,'GNB','Guinea-Bissau, Republik','Guinea-bissau','Bissau','GBS','Afrika','.gw','XOF','+245',0,0)
,('GY',null,'GUY','Guyana','Guyana','Georgetown','GUY','Südamerika','.gy','GYD','+592',0,0)
,('HT',null,'HTI','Haiti','Haiti','Port-au-Prince','HAI','Nordamerika','.ht','USD','+59',0,0)
,('HM',null,'HMD','Heard und McDonaldinseln','Heard Island And Mcdonald Islands',null,null,'Australien','.hm','AUD',null,0,0)
,('HN',null,'HND','Honduras','Honduras','Tegucigalpa','HON','Nordamerika','.hn','HNL','+54',0,0)
,('HK',null,'HKG','Hongkong','Hong Kong',null,'HKG','Asien','.hk','HNL','+852',0,0)
,('IN',null,'IND','Indien','India','Neu-Delhi','IND','Asien','.in','ISK','+91',0,0)
,('ID',null,'IDN','Indonesien','Indonesia','Jakarta','INA','Asien','.id','INR','+62',0,0)
,('IM',null,'IMN','Insel Man','Isle Of Man',null,null,null,'.im','IMP','+44',0,0)
,('IQ',null,'IRQ','Irak','Iraq','Bagdad','IRQ','Asien','.iq','IDR','+964',0,0)
,('IR',null,'IRN','Iran','Iran, Islamic Republic Of','Teheran','IRI','Asien','.ir','IRR','+98',0,0)
,('IE',null,'IRL','Irland, Republik','Ireland','Dublin','IRL','Europa','.ie','EUR','+353',1,0)
,('IS',null,'ISL','Island','Iceland','Reykjavík','ISL','Europa','.is','HUF','+354',1,0)
,('IL',null,'ISR','Israel','Israel','Jerusalem','ISR','Asien','.il','ILS','+972',0,0)
,('IT',null,'ITA','Italien','Italy','Rom','ITA','Europa','.it','EUR','+39',1,0)
,('JM',null,'JAM','Jamaika','Jamaica','Kingston','JAM','Nordamerika','.jm','JMD','+1876',0,0)
,('JP',null,'JPN','Japan','Japan','Tokio','JPN','Asien','.jp','JPY','+81',0,0)
,('YE',null,'YEM','Jemen','Yemen','Sanaa','YEM','Asien','.ye','YER','+967',0,0)
,('JE',null,'JEY','Jersey','Jersey','Saint Helier',null,'Europa','.je','JEP','+44',0,0)
,('JO',null,'JOR','Jordanien','Jordan','Amman','JOR','Asien','.jo','JOD','+962',0,0)
,('KY',null,'CYM','Kaimaninseln','Cayman Islands','George Town','CAY','Nordamerika','.ky','KYD','+1345',0,0)
,('KH',null,'KHM','Kambodscha','Cambodia','Phnom Penh','CAM','Asien','.kh','KHR','+855',0,0)
,('CM',null,'CMR','Kamerun','Cameroon','Yaoundé','CMR','Afrika','.cm','XAF','+237',0,0)
,('CA',null,'CAN','Kanada','Canada','Ottawa','CAN','Nordamerika','.ca','CAD','+1NXX',0,0)
,('IC',null,null,'Kanarische Inseln',null,null,null,'Europa',null,null,null,0,0)
,('CV',null,'CPV','Kap Verde, Republik','Cape Verde','Praia','CPV','Afrika','.cv','CVE','+238',0,0)
,('KZ',null,'KAZ','Kasachstan','Kazakhstan','Astana','KAZ','Asien','.kz','KZT','+7',0,0)
,('QA',null,'QAT','Katar','Qatar','Doha','QAT','Asien','.qa','QAR','+974',0,0)
,('KE',null,'KEN','Kenia','Kenya','Nairobi','KEN','Afrika','.ke','KES','+254',0,0)
,('KG',null,'KGZ','Kirgisistan','Kyrgyzstan','Bischkek','KGZ','Asien','.kg','KGS','+996',0,0)
,('KI',null,'KIR','Kiribati','Kiribati','Bairiki',null,'Australien','.ki','AUD','+686',0,0)
,('CC',null,'CCK','Kokosinseln','Cocos (keeling) Islands',null,null,'Asien','.cc','AUD',null,0,0)
,('CO',null,'COL','Kolumbien','Colombia','Santa Fé de Bogotá','COL','Südamerika','.co','COP','+57',0,0)
,('KM',null,null,'Komoren','Comoros','Moroni',null,'Afrika','.km','KMF','+269',0,0)
,('CD',null,'COD','Kongo, Demokratische Republik','Congo, The Democratic Republic Of The','Kinshasa','COD','Afrika','.cd','CDF','+243',0,0)
,('CG',null,'COG','Kongo, Republik','Congo','Brazzaville','CGO','Afrika','.cg','XAF','+242',0,0)
,('KP',null,'PRK','Korea, Demokratische Volkrepublik','Korea, Democratic People\'s Republic Of','Pjöngjang','PRK','Asien','.kp','KPW','+850',0,0)
,('KR',null,'KOR','Korea, Republik','Korea, Republic Of','Seoul','KOR','Asien','.kr','KRW','+82',0,0)
,('HR',null,'HRV','Kroatien','Croatia','Zagreb','CRO','Europa','.hr','HRK','+385',1,0)
,('CU',null,'CUB','Kuba','Cuba','Havanna','CUB','Nordamerika','.cu','CUP','+53',0,0)
,('KW',null,'KWT','Kuwait','Kuwait','Kuwait','KUW','Asien','.kw','KWD','+965',0,0)
,('LA',null,'LAO','Laos','Lao People\'s Democratic Republic','Vientiane','LAO','Asien','.la','LAK','+856',0,0)
,('LS',null,'LSO','Lesotho','Lesotho','Maseru','LES','Afrika','.ls','LSL','+266',0,0)
,('LV',null,'LVA','Lettland','Latvia','R?ga','LAT','Europa','.lv','LVL','+371',1,0)
,('LB',null,'LBN','Libanon','Lebanon','Beirut','LIB','Asien','.lb','LBP','+961',0,0)
,('LR',null,'LBR','Liberia, Republik','Liberia','Monrovia','LBR','Afrika','.lr','LRD','+231',0,0)
,('LY',null,'LBY','Libyen','Libyan Arab Jamahiriya','Tripolis','LBA','Afrika','.ly','LYD','+218',0,0)
,('LI',null,'LIE','Liechtenstein, Fürstentum','Liechtenstein','Vaduz','LIE','Europa','.li','CHF','+423',0,0)
,('LT',null,'LTU','Litauen','Lithuania','Wilna','LTU','Europa','.lt','LTL','+370',1,0)
,('LU',null,'LUX','Luxemburg','Luxembourg','Luxemburg','LUX','Europa','.lu','EUR','+352',1,0)
,('MO',null,'MAC','Macao','Macao',null,null,'Asien','.mo','MOP','+853',0,0)
,('MG',null,'MDG','Madagaskar, Republik','Madagascar','Antananarivo','MAD','Afrika','.mg','MGA','+261',0,0)
,('MW',null,'MWI','Malawi, Republik','Malawi','Lilongwe','MAW','Afrika','.mw','MWK','+265',0,0)
,('MY',null,'MYS','Malaysia','Malaysia','Kuala Lumpur','MAS','Asien','.my','MYR','+60',0,0)
,('MV',null,'MDV','Malediven','Maldives','Malé','MDV','Asien','.mv','MVR','+960',0,0)
,('ML',null,'MLI','Mali, Republik','Mali','Bamako','MLI','Afrika','.ml','XOF','+223',0,0)
,('MT',null,'MLT','Malta','Malta','Valletta','MLT','Europa','.mt','EUR','+356',1,0)
,('MA',null,'MAR','Marokko','Morocco','Rabat','MAR','Afrika','.ma','MAD','+211',0,0)
,('MH',null,'MHL','Marshallinseln','Marshall Islands','Delap-Uliga-Darrit',null,'Australien','.mh','USD','+692',0,0)
,('MQ',null,'MTQ','Martinique','Martinique','Fort-de-France',null,'Nordamerika','.mq','EUR','+596',0,0)
,('MR',null,'MRT','Mauretanien','Mauritania','Nouakchott','MTN','Afrika','.mr','MRO','+222',0,0)
,('MU',null,'MUS','Mauritius, Republik','Mauritius','Port Louis','MRI','Afrika','.mu','MUR','+230',0,0)
,('YT',null,'MYT','Mayotte','Mayotte','Mamoudzou',null,'Afrika','.yt','EUR','+269',0,0)
,('MK',null,'MKD','Mazedonien','Macedonia, The Former Yugoslav Republic Of','Skopje','MKD','Europa','.mk','MKD','+389',1,0)
,('MX',null,'MEX','Mexiko','Mexico','Mexiko-Stadt','MEX','Nordamerika','.mx','MXN','+52',0,0)
,('FM',null,'FSM','Mikronesien, Föderierte Staaten von','Micronesia, Federated States Of',null,'FSM','Australien','.fm','USD','+691',0,0)
,('MD',null,'MDA','Moldawien','Moldova','Chi?in?u','MDA','Europa','.md','MDL','+373',0,0)
,('MC',null,'MCO','Monaco','Monaco','Monaco','MON','Europa','.mc','EUR','+377',0,0)
,('MN',null,'MNG','Mongolei','Mongolia','Ulaanbaatar','MGL','Asien','.mn','MNT','+976',0,0)
,('MS',null,'MSR','Montserrat','Montserrat','Plymouth',null,'Nordamerika','.ms','XCD','+1664',0,0)
,('MZ',null,'MOZ','Mosambik','Mozambique','Maputo','MOZ','Afrika','.mz','MZM','+258',0,0)
,('MM',null,'MMR','Myanmar','Myanmar','Rangun','MYA','Asien','.mm','MMK','+95',0,0)
,('NA',null,'NAM','Namibia, Republik','Namibia','Windhoek','NAM','Afrika','.na','ZAR','+264',0,0)
,('NR',null,'NRU','Nauru','Nauru','Yaren','NRU','Australien','.nr','AUD','+674',0,0)
,('NP',null,'NPL','Nepal','Nepal','Kathmandu','NEP','Asien','.np','NPR','+977',0,0)
,('NC',null,'NCL','Neukaledonien','New Caledonia','Nouméa',null,'Australien','.nc','XPF','+687',0,0)
,('NZ',null,'NZL','Neuseeland','New Zealand','Wellington','NZL','Australien','.nz','NZD','+64',0,0)
,('NT',null,'NTZ','Neutrale Zone',null,null,null,'Asien','.nt',null,null,0,0)
,('NI',null,'NIC','Nicaragua','Nicaragua','Managua','NCA','Nordamerika','.ni','NIO','+55',0,0)
,('NL',null,'NLD','Niederlande','Netherlands','Amsterdam','NED','Europa','.nl','EUR','+31',1,0)
,('AN',null,'ANT','Niederländische Antillen','Netherlands Antilles','Willemstad','AHO','Nordamerika','.an','ANG','+599',0,0)
,('NE',null,'NER','Niger','Niger','Niamey','NIG','Afrika','.ne','XOF','+227',0,0)
,('NG',null,'NGA','Nigeria','Nigeria','Abuja','NGR','Afrika','.ng','NGN','+234',0,0)
,('NU',null,'NIU','Niue','Niue','Alofi',null,'Australien','.nu','NZD','+683',0,0)
,('MP',null,'MNP','Nördliche Marianen','Northern Mariana Islands','Saipan',null,'Australien','.mp','USD','+1670',0,0)
,('NF',null,'NFK','Norfolkinsel','Norfolk Island','Kingston',null,'Australien','.nf','AUD','+6723',0,0)
,('NO',null,'NOR','Norwegen','Norway','Oslo','NOR','Europa','.no','NOK','+47',0,0)
,('OM',null,'OMN','Oman','Oman','Maskat','OMA','Asien','.om','OMR','+968',0,0)
,('AT','de-at','AUT','Österreich','Austria','Wien','AUT','Europa','.at','EUR','+43',1,1)
,('PK',null,'PAK','Pakistan','Pakistan','Islamabad','PAK','Asien','.pk','PKR','+92',0,0)
,('PS',null,'PSE','Palästinensische Autonomiegebiete','Palestinian Territory, Occupied','Ramallah','PLE','Asien','.ps',null,'+970',0,0)
,('PW',null,'PLW','Palau','Palau','Melekeok','PLW','Australien','.pw','USD','+680',0,0)
,('PA',null,'PAN','Panama','Panama','Panama-Stadt','PAN','Südamerika','.pa','USD','+57',0,0)
,('PG',null,'PNG','Papua-Neuguinea','Papua New Guinea','Port Moresby',null,'Australien','.pg','PGK','+675',0,0)
,('PY',null,'PRY','Paraguay','Paraguay','Asunción','PAR','Südamerika','.py','PYG','+595',0,0)
,('PE',null,'PER','Peru','Peru','Lima','PER','Südamerika','.pe','PEN','+51',0,0)
,('PH',null,'PHL','Philippinen','Philippines','Manila','PHI','Asien','.ph','PHP','+63',0,0)
,('PN',null,'PCN','Pitcairninseln','Pitcairn','Adamstown',null,'Australien','.pn','NZD','+649',0,0)
,('PL',null,'POL','Polen','Poland','Warschau','POL','Europa','.pl','PLN','+48',0,0)
,('PT',null,'PRT','Portugal','Portugal','Lissabon','POR','Europa','.pt','EUR','+351',1,0)
,('PR',null,'PRI','Puerto Rico','Puerto Rico','San Juan','PUR','Nordamerika','.pr','USD','+1939',0,0)
,('RE',null,'REU','Réunion','RÉunion','Saint-Denis',null,'Afrika','.re','EUR','+262',0,0)
,('RW',null,'RWA','Ruanda, Republik','Rwanda','Kigali','RWA','Afrika','.rw','RWF','+250',0,0)
,('RO',null,'ROU','Rumänien','Romania','Bukarest','ROM','Europa','.ro','RON','+40',1,0)
,('RU',null,'RUS','Russische Föderation','Russian Federation','Moskau','RUS','Asien','.ru','RUB','+7',0,0)
,('SB',null,'SLB','Salomonen','Solomon Islands','Honiara','SOL','Australien','.sb','SBD','+677',0,0)
,('ZM',null,'ZMB','Sambia, Republik','Zambia','Lusaka','ZAM','Afrika','.zm','ZMK','+260',0,0)
,('WS',null,'WSM','Samoa','Samoa','Apia','SAM','Australien','.ws','WST',null,0,0)
,('SM',null,'SMR','San Marino','San Marino','San Marino','SMR','Europa','.sm','EUR','+378',0,0)
,('ST',null,'STP','São Tomé und Príncipe','Sao Tome And Principe','São Tomé','STP','Afrika','.st','STD','+239',0,0)
,('SA',null,'SAU','Saudi-Arabien, Königreich','Saudi Arabia','Riad','KSA','Asien','.sa','SAR','+966',0,0)
,('SE',null,'SWE','Schweden','Sweden','Stockholm','SWE','Europa','.se','SEK','+46',1,0)
,('CH','de-ch','CHE','Schweiz','Switzerland','Bern','SUI','Europa','.ch','CHF','+41',0,0)
,('SN',null,'SEN','Senegal','Senegal','Dakar','SEN','Afrika','.sn','XOF','+221',0,0)
,('CS',null,'SCG','Serbien und Montenegro','Serbia','Belgrad','YUG','Europa','.cs',null,'+381',0,0)
,('SC',null,'SYC','Seychellen, Republik der','Seychelles','Victoria','SEY','Afrika','.sc','SCR','+248',0,0)
,('SL',null,'SLE','Sierra Leone, Republik','Sierra Leone','Freetown','SLE','Afrika','.sl','SLL','+232',0,0)
,('ZW',null,'ZWE','Simbabwe, Republik','Zimbabwe','Harare','ZIM','Afrika','.zw','ZWD','+263',0,0)
,('SG',null,'SGP','Singapur','Singapore','Singapur','SIN','Asien','.sg','SGD','+65',0,0)
,('SK',null,'SVK','Slowakei','Slovakia','Bratislava','SVK','Europa','.sk','SKK','+421',1,0)
,('SI',null,'SVN','Slowenien','Slovenia','Ljubljana','SLO','Europa','.si','SIT','+386',1,0)
,('SO',null,'SOM','Somalia, Demokratische Republik','Somalia','Mogadischu','SOM','Afrika','.so','SOS','+252',0,0)
,('ES',null,'ESP','Spanien','Spain','Madrid','ESP','Europa','.es','EUR','+34',1,0)
,('LK',null,'LKA','Sri Lanka','Sri Lanka','Colombo','SRI','Asien','.lk','LKR','+94',0,0)
,('KN',null,'KNA','St. Kitts und Nevis','Saint Kitts And Nevis','Basseterre','SKN','Nordamerika','.kn','XCD','+1869',0,0)
,('LC',null,'LCA','St. Lucia','Saint Lucia','Castries','LCA','Südamerika','.lc','XCD','+1758',0,0)
,('PM',null,'SPM','St. Pierre und Miquelon','Saint Pierre And Miquelon','Saint-Pierre',null,'Nordamerika','.pm','EUR','+508',0,0)
,('VC',null,'VCT','St. Vincent und die Grenadinen (GB)','Saint Vincent And The Grenadines','Kingstown','VIN','Südamerika','.vc','XCD','+1784',0,0)
,('ZA',null,'ZAF','Südafrika, Republik','South Africa','Tshwane / Pretoria','RSA','Afrika','.za','ZAR','+27',0,0)
,('SD',null,'SDN','Sudan','Sudan','Khartum','SUD','Afrika','.sd','SDD','+249',0,0)
,('GS',null,'SGS','Südgeorgien und die Südlichen Sandwichinseln','South Georgia And The South Sandwich Islands','Grytviken',null,null,null,'GBP',null,0,0)
,('SR',null,'SUR','Suriname','Suriname','Paramaribo','SUR','Südamerika','.sr','SRD','+597',0,0)
,('SJ',null,'SJM','Svalbard und Jan Mayen','Svalbard And Jan Mayen','Longyearbyen',null,'Europa','.sj','NOK',null,0,0)
,('SZ',null,'SWZ','Swasiland','Swaziland','Mbabane','SWZ','Afrika','.sz','SZL','+268',0,0)
,('SY',null,'SYR','Syrien','Syrian Arab Republic','Damaskus','SYR','Asien','.sy','SYP','+963',0,0)
,('TJ',null,'TJK','Tadschikistan','Tajikistan','Duschanbe','TJK','Asien','.tj','RUB','+992',0,0)
,('TW',null,'TWN','Taiwan','Taiwan, Province Of China','Taipeh','TPE','Asien','.tw','TWD','+886',0,0)
,('TZ',null,'TZA','Tansania, Vereinigte Republik','Tanzania, United Republic Of','Dodoma','TAN','Afrika','.tz','TZS','+255',0,0)
,('TH',null,'THA','Thailand','Thailand','Bangkok','THA','Asien','.th','THB','+66',0,0)
,('TL',null,'TLS','Timor-Leste, Demokratische Republik','Timor-leste','Dili',null,'Australien','.tl','IDR','+670',0,0)
,('TG',null,'TGO','Togo, Republik','Togo','Lomé','TOG','Afrika','.tg','XOF','+228',0,0)
,('TK',null,'TKL','Tokelau','Tokelau','-/-',null,'Australien','.tk','NZD','+690',0,0)
,('TO',null,'TON','Tonga','Tonga','Nuku’alofa','TGA','Australien','.to','TOP','+676',0,0)
,('TT',null,'TTO','Trinidad und Tobago','Trinidad And Tobago','Port-of-Spain','TRI','Südamerika','.tt','TTD','+1868',0,0)
,('TA',null,'TAA','Tristan da Cunha',null,'Jamestown',null,'Afrika',null,null,'+290',0,0)
,('TD',null,'TCD','Tschad, Republik','Chad','N\'Djamena','CHA','Afrika','.td','XAF','+235',0,0)
,('CZ',null,'CZE','Tschechische Republik','Czech Republic','Prag','CZE','Europa','.cz','CZK','+420',1,0)
,('TN',null,'TUN','Tunesien','Tunisia','Tunis','TUN','Afrika','.tn','TND','+216',0,0)
,('TR',null,'TUR','Türkei','Turkey','Ankara','TUR','Asien','.tr','TRY','+90',1,0)
,('TM',null,'TKM','Turkmenistan','Turkmenistan','A?gabat','TKM','Asien','.tm','TMM','+993',0,0)
,('TC',null,'TCA','Turks- und Caicosinseln','Turks And Caicos Islands','Cockburn Town auf Grand Turk',null,'Nordamerika','.tc','USD','+1649',0,0)
,('TV',null,'TUV','Tuvalu','Tuvalu','Funafuti',null,'Australien','.tv','TVD','+688',0,0)
,('UG',null,'UGA','Uganda, Republik','Uganda','Kampala','UGA','Afrika','.ug','UGX','+256',0,0)
,('UA',null,'UKR','Ukraine','Ukraine','Kiew','UKR','Europa','.ua','UAH','+380',0,0)
,('SU',null,'SUN','Union der Sozialistischen Sowjetrepubliken',null,'Moskau','URS',null,'.su',null,null,0,0)
,('UY',null,'URY','Uruguay','Uruguay','Montevideo','URU','Südamerika','.uy','UYU','+598',0,0)
,('UZ',null,'UZB','Usbekistan','Uzbekistan','Taschkent','UZB','Asien','.uz','UZS','+998',0,0)
,('VU',null,'VUT','Vanuatu','Vanuatu','Port Vila','VAN','Australien','.vu','VUV','+678',0,0)
,('VA',null,'VAT','Vatikanstadt','Holy See (vatican City State)','Vatikanstadt',null,'Europa','.va','EUR','+3906',0,0)
,('VE',null,'VEN','Venezuela','Venezuela','Caracas','VEN','Südamerika','.ve','VEB','+58',0,0)
,('AE',null,'ARE','Vereinigte Arabische Emirate','United Arab Emirates','Abu Dhabi','UAE','Asien','.ae','AED','+971',0,0)
,('US','en-us','USA','Vereinigte Staaten von Amerika','United States','Washington, D.C.','USA','Nordamerika','.us','USD','+1',0,0)
,('GB','en-gb','GBR','Großbritannien und Nordirland','United Kingdom','London','GBR','Europa','.gb','GBP','+44',1,0)
,('VN',null,'VNM','Vietnam','Viet Nam','Hà N?i','VIE','Asien','.vn','VND','+84',0,0)
,('WF',null,'WLF','Wallis und Futuna','Wallis And Futuna','Mata-Utu',null,'Australien','.wf','XPF','+681',0,0)
,('CX',null,'CXR','Weihnachtsinsel','Christmas Island','Flying Fish Cove',null,'Asien','.cx','AUD',null,0,0)
,('BY',null,'BLR','Weißrussland','Belarus','Minsk','BLR','Europa','.by','BYR','+375',0,0)
,('EH',null,'ESH','Westsahara','Western Sahara','El Aaiún',null,'Afrika','.eh','MAD',null,0,0)
,('CF',null,'CAF','Zentralafrikanische Republik','Central African Republic','Bangui','CAF','Afrika','.cf','XAF','+236',0,0)
,('CY',null,'CYP','Zypern, Republik','Cyprus','Nikosia','CYP','Asien','.cy','CYP','+357',0,0)
,('HU',null,'HUN','Ungarn','Hungary','Budapest','HUN','Europa','.hu','HUF','+36',1,0)
,('ME',null,'MNE','Montenegro',null,'Podgorica','MNE','Europa','.me',null,'+382',0,0)
