USE ticketing_db;

DROP TABLE IF EXISTS `feLang`;
CREATE TABLE `feLang` (
  `LangISO2` varchar(2) NOT NULL,
  `LangName` varchar(200) NOT NULL DEFAULT '',
  `LangISO3` varchar(3) NOT NULL,
  `LangDE` varchar(200) NOT NULL,
  `LangEN` varchar(200) NOT NULL,
  `LangCapital` varchar(200) NOT NULL,
  `LangIOC` varchar(3) NOT NULL,
  `LangContinent` varchar(100) NOT NULL,
  `LangDomain` varchar(6) NOT NULL,
  `LangCurrancy` varchar(5) NOT NULL,
  `LangAreaCode` varchar(10) NOT NULL,
  `LangEU` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `LangLocale` tinyint(1) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`LangISO2`),
  UNIQUE KEY `LangISO2_UNIQUE` (`LangISO2`)
)
ENGINE = MyISAM DEFAULT CHARSET=UTF8MB4;

INSERT INTO feLang VALUES ('AF','','AFG','Afghanistan','Afghanistan','Kabul','AFG','Asien','.af','AFN','+93',0,0)
,('EG','','EGY','Ägypten','Egypt','Kairo','EGY','Afrika','.eg','EGP','+20',0,0)
,('AX','','ALA','Aland','Åland Islands','Mariehamn','','Europa','.ax','EUR','+35818',0,0)
,('AL','','ALB','Albanien','Albania','Tirana','ALB','Europa','.al','ALL','+355',0,0)
,('DZ','','DZA','Algerien','Algeria','Algier','ALG','Afrika','.dz','DZD','+213',0,0)
,('AS','','ASM','Amerikanisch-Samoa','American Samoa','Pago-Pago','','Australien','.as','USD','+1684',0,0)
,('VI','','VIR','Amerikanische Jungferninseln','Virgin Islands, U.s.','Charlotte Amalie','','Südamerika','.vi','USD','+1340',0,0)
,('AD','','AND','Andorra','Andorra','Andorra la Vella','AND','Europa','.ad','EUR','+376',0,0)
,('AO','','AGO','Angola','Angola','Luanda','ANG','Afrika','.ao','AOA','+244',0,0)
,('AI','','AIA','Anguilla','Anguilla','The Valley','','Nordamerika','.ai','XCD','+1264',0,0)
,('AQ','','ATA','Antarktis','Antarctica','Juneau','','Antarktika','.aq','','+672',0,0)
,('AG','','ATG','Antigua und Barbuda','Antigua And Barbuda','Saint John\'s','ANT','Nordamerika','.ag','XCD','+1268',0,0)
,('GQ','','GNQ','Äquatorialguinea, Republik','Equatorial Guinea','Malabo','GEQ','Afrika','.gq','XAF','+240',0,0)
,('AR','','ARG','Argentinien','Argentina','Buenos Aires','ARG','Südamerika','.ar','ARS','+54',0,0)
,('AM','','ARM','Armenien','Armenia','Eriwan','ARM','Asien','.am','AMD','+374',0,0)
,('AW','','ABW','Aruba','Aruba','Oranjestad','ARU','Nordamerika','.aw','ANG','+297',0,0)
,('AC','','ASC','Ascension','','-/-','','Afrika','.ac','','+247',0,0)
,('AZ','','AZE','Aserbaidschan','Azerbaijan','Baku','AZE','Asien','.az','AZN','+994',0,0)
,('ET','','ETH','Äthiopien','Ethiopia','Addis Abeba','ETH','Afrika','.et','ETB','+251',0,0)
,('AU','','AUS','Australien','Australia','Canberra','AUS','Australien','.au','AUD','+61',0,0)
,('BS','','BHS','Bahamas','Bahamas','Nassau','BAH','Nordamerika','.bs','BSD','+1242',0,0)
,('BH','','BHR','Bahrain','Bahrain','Manama','BRN','Asien','.bh','BHD','+973',0,0)
,('BD','','BGD','Bangladesch','Bangladesh','Dhaka','BAN','Asien','.bd','BDT','+880',0,0)
,('BB','','BRB','Barbados','Barbados','Bridgetown','BAR','Nordamerika','.bb','BBD','+1246',0,0)
,('BE','','BEL','Belgien','Belgium','Brüssel','BEL','Europa','.be','EUR','+32',1,0)
,('BZ','','BLZ','Belize','Belize','Belmopan','BLZ','Nordamerika','.bz','BZD','+51',0,0)
,('BJ','','BEN','Benin','Benin','Porto Novo','BEN','Afrika','.bj','XOF','+229',0,0)
,('BM','','BMU','Bermuda','Bermuda','Hamilton','BER','Nordamerika','.bm','BMD','+1441',0,0)
,('BT','','BTN','Bhutan','Bhutan','Thimphu','BHU','Asien','.bt','BTN','+975',0,0)
,('BO','','BOL','Bolivien','Bolivia','Sucre','BOL','Südamerika','.bo','BOB','+591',0,0)
,('BA','','BIH','Bosnien und Herzegowina','Bosnia And Herzegovina','Sarajevo','BIH','Europa','.ba','BAM','+387',0,0)
,('BW','','BWA','Botswana','Botswana','Gaborone','BOT','Afrika','.bw','BWP','+267',0,0)
,('BV','','BVT','Bouvetinsel','Bouvet Island','(Forschungsinsel)','','Antarktika','.bv','NOK','',0,0)
,('BR','','BRA','Brasilien','Brazil','Brasília','BRA','Südamerika','.br','BRL','+55',0,0)
,('VG','','VGB','Britische Jungferninseln','Virgin Islands, British','Road Town','ISB','Nordamerika','.vg','USD','+1284',0,0)
,('IO','','IOT','Britisches Territorium im Indischen Ozean','British Indian Ocean Territory','-/-','','Asien','.io','USD','',0,0)
,('BN','','BRN','Brunei','Brunei Darussalam','Bandar Seri Begawan','BRU','Asien','.bn','BND','+673',0,0)
,('BG','','BGR','Bulgarien','Bulgaria','Sofia','BUL','Europa','.bg','BGN','+359',1,0)
,('BF','','BFA','Burkina Faso','Burkina Faso','Ouagadougou','BUR','Afrika','.bf','XOF','+226',0,0)
,('BI','','BDI','Burundi','Burundi','Bujumbura','BDI','Afrika','.bi','BIF','+257',0,0)
,('CL','','CHL','Chile','Chile','Santiago','CHI','Südamerika','.cl','CLP','+56',0,0)
,('CN','','CHN','China, Volksrepublik','China','Peking (Beijing)','CHN','Asien','.cn','CNY','+86',0,0)
,('CK','','COK','Cookinseln','Cook Islands','Avarua','COK','Australien','.ck','NZD','+682',0,0)
,('CR','','CRI','Costa Rica','Costa Rica','San José','CRC','Nordamerika','.cr','CRC','+56',0,0)
,('CI','','CIV','Cote d´Ivoire','CÔte D\'ivoire','Yamoussoukro','CIV','Afrika','.ci','XOF','+225',0,0)
,('DK','','DNK','Dänemark','Denmark','Kopenhagen','DEN','Europa','.dk','DKK','+45',1,0)
,('DE','','DEU','Deutschland','Germany','Berlin','GER','Europa','.de','EUR','+49',1,0)
,('SH','','SHN','St. Helena und Nebengebiete','Saint Helena','Jamestown','','Afrika','.sh','SHP','+290',0,0)
,('DG','','DGA','Diego Garcia','','','','Afrika','','','+246',0,0)
,('DM','','DMA','Dominica','Dominica','Roseau','','Nordamerika','.dm','XCD','+1767',0,0)
,('DO','','DOM','Dominikanische Republik','Dominican Republic','Santo Domingo','DOM','Südamerika','.do','DOP','+1809',0,0)
,('DJ','','DJI','Dschibuti','Djibouti','Dschibuti','DJI','Afrika','dj','DJF','+253',0,0)
,('EC','','ECU','Ecuador','Ecuador','Quito','ECU','Südamerika','.ec','USD','+593',0,0)
,('SV','','SLV','El Salvador','El Salvador','San Salvador','ESA','Nordamerika','.sv','SVC','+53',0,0)
,('ER','','ERI','Eritrea','Eritrea','Asmara (Asmera)','ERI','Afrika','.er','ERN','+291',0,0)
,('EE','','EST','Estland','Estonia','Tallinn (Reval)','EST','Europa','.ee','EEK','+372',1,0)
,('EU','','-/-','Europäische Union','','Brüssel','-/-','Europa','.eu','','+3883',0,0)
,('FK','','FLK','Falklandinseln','Falkland Islands (malvinas)','Port Stanley','','Afrika','.fk','FLP','+500',0,0)
,('FO','','FRO','Färöer','Faroe Islands','Tórshavn','FRO','Europa','.fo','DKK','+298',0,0)
,('FJ','','FJI','Fidschi','Fiji','Suva','FJI','Australien','.fj','FJD','+679',0,0)
,('FI','','FIN','Finnland','Finland','Helsinki','FIN','Europa','.fi','EUR','+358',1,0)
,('FR','','FRA','Frankreich','France','Paris','FRA','Europa','.fr','EUR','+33',1,0)
,('GF','','GUF','Französisch-Guayana','French Guiana','Cayenne','','Südamerika','.gf','EUR','+594',0,0)
,('PF','','PYF','Französisch-Polynesien','French Polynesia','Papeete','','Australien','.pf','XPF','+689',0,0)
,('TF','','ATF','Französische Süd- und Antarktisgebiete','French Southern Territories','Port-aux-Français','','','.tf','EUR','',0,0)
,('GA','','GAB','Gabun','Gabon','Libreville','GAB','Afrika','.ga','XAF','+241',0,0)
,('GM','','GMB','Gambia','Gambia','Banjul','GAM','Afrika','.gm','GMD','+220',0,0)
,('GE','','GEO','Georgien','Georgia','Tiflis','GEO','Europa','.ge','GEL','+995',0,0)
,('GH','','GHA','Ghana, Republik','Ghana','Accra','GHA','Afrika','.gh','GHC','+233',0,0)
,('GI','','GIB','Gibraltar','Gibraltar','Gibraltar (Stadt)','','Afrika','.gi','GIP','+350',0,0)
,('GD','','GRD','Grenada','Grenada','St. George\'s','GRN','Nordamerika','.gd','XCD','+1473',0,0)
,('GR','','GRC','Griechenland','Greece','Athen','GRE','Europa','.gr','EUR','+30',1,0)
,('GL','','GRL','Grönland','Greenland','Nuuk','','Nordamerika','.gl','DKK','+299',0,0)
,('GP','','GLP','Guadeloupe','','Basse-Terre','','Nordamerika','.gp','EUR','+590',0,0)
,('GU','','GUM','Guam','Guam','Hagåtña','GUM','Asien','.gu','USD','+1671',0,0)
,('GT','','GTM','Guatemala','Guatemala','Guatemala-Stadt','GUA','Nordamerika','.gt','GTQ','+52',0,0)
,('GG','','GGY','Guernsey, Vogtei','Guernsey','St. Peter Port','','Europa','.gg','GGP','+44',0,0)
,('GN','','GIN','Guinea, Republik','Guinea','Conakry','GUI','Afrika','.gn','GNF','+224',0,0)
,('GW','','GNB','Guinea-Bissau, Republik','Guinea-bissau','Bissau','GBS','Afrika','.gw','XOF','+245',0,0)
,('GY','','GUY','Guyana','Guyana','Georgetown','GUY','Südamerika','.gy','GYD','+592',0,0)
,('HT','','HTI','Haiti','Haiti','Port-au-Prince','HAI','Nordamerika','.ht','USD','+59',0,0)
,('HM','','HMD','Heard und McDonaldinseln','Heard Island And Mcdonald Islands','','','Australien','.hm','AUD','',0,0)
,('HN','','HND','Honduras','Honduras','Tegucigalpa','HON','Nordamerika','.hn','HNL','+54',0,0)
,('HK','','HKG','Hongkong','Hong Kong','','HKG','Asien','.hk','HNL','+852',0,0)
,('IN','','IND','Indien','India','Neu-Delhi','IND','Asien','.in','ISK','+91',0,0)
,('ID','','IDN','Indonesien','Indonesia','Jakarta','INA','Asien','.id','INR','+62',0,0)
,('IM','','IMN','Insel Man','Isle Of Man','','','','.im','IMP','+44',0,0)
,('IQ','','IRQ','Irak','Iraq','Bagdad','IRQ','Asien','.iq','IDR','+964',0,0)
,('IR','','IRN','Iran','Iran, Islamic Republic Of','Teheran','IRI','Asien','.ir','IRR','+98',0,0)
,('IE','','IRL','Irland, Republik','Ireland','Dublin','IRL','Europa','.ie','EUR','+353',1,0)
,('IS','','ISL','Island','Iceland','Reykjavík','ISL','Europa','.is','HUF','+354',1,0)
,('IL','','ISR','Israel','Israel','Jerusalem','ISR','Asien','.il','ILS','+972',0,0)
,('IT','','ITA','Italien','Italy','Rom','ITA','Europa','.it','EUR','+39',1,0)
,('JM','','JAM','Jamaika','Jamaica','Kingston','JAM','Nordamerika','.jm','JMD','+1876',0,0)
,('JP','','JPN','Japan','Japan','Tokio','JPN','Asien','.jp','JPY','+81',0,0)
,('YE','','YEM','Jemen','Yemen','Sanaa','YEM','Asien','.ye','YER','+967',0,0)
,('JE','','JEY','Jersey','Jersey','Saint Helier','','Europa','.je','JEP','+44',0,0)
,('JO','','JOR','Jordanien','Jordan','Amman','JOR','Asien','.jo','JOD','+962',0,0)
,('KY','','CYM','Kaimaninseln','Cayman Islands','George Town','CAY','Nordamerika','.ky','KYD','+1345',0,0)
,('KH','','KHM','Kambodscha','Cambodia','Phnom Penh','CAM','Asien','.kh','KHR','+855',0,0)
,('CM','','CMR','Kamerun','Cameroon','Yaoundé','CMR','Afrika','.cm','XAF','+237',0,0)
,('CA','','CAN','Kanada','Canada','Ottawa','CAN','Nordamerika','.ca','CAD','+1NXX',0,0)
,('IC','','','Kanarische Inseln','','','','Europa','','','',0,0)
,('CV','','CPV','Kap Verde, Republik','Cape Verde','Praia','CPV','Afrika','.cv','CVE','+238',0,0)
,('KZ','','KAZ','Kasachstan','Kazakhstan','Astana','KAZ','Asien','.kz','KZT','+7',0,0)
,('QA','','QAT','Katar','Qatar','Doha','QAT','Asien','.qa','QAR','+974',0,0)
,('KE','','KEN','Kenia','Kenya','Nairobi','KEN','Afrika','.ke','KES','+254',0,0)
,('KG','','KGZ','Kirgisistan','Kyrgyzstan','Bischkek','KGZ','Asien','.kg','KGS','+996',0,0)
,('KI','','KIR','Kiribati','Kiribati','Bairiki','','Australien','.ki','AUD','+686',0,0)
,('CC','','CCK','Kokosinseln','Cocos (keeling) Islands','','','Asien','.cc','AUD','',0,0)
,('CO','','COL','Kolumbien','Colombia','Santa Fé de Bogotá','COL','Südamerika','.co','COP','+57',0,0)
,('KM','','','Komoren','Comoros','Moroni','','Afrika','.km','KMF','+269',0,0)
,('CD','','COD','Kongo, Demokratische Republik','Congo, The Democratic Republic Of The','Kinshasa','COD','Afrika','.cd','CDF','+243',0,0)
,('CG','','COG','Kongo, Republik','Congo','Brazzaville','CGO','Afrika','.cg','XAF','+242',0,0)
,('KP','','PRK','Korea, Demokratische Volkrepublik','Korea, Democratic People\'s Republic Of','Pjöngjang','PRK','Asien','.kp','KPW','+850',0,0)
,('KR','','KOR','Korea, Republik','Korea, Republic Of','Seoul','KOR','Asien','.kr','KRW','+82',0,0)
,('HR','','HRV','Kroatien','Croatia','Zagreb','CRO','Europa','.hr','HRK','+385',1,0)
,('CU','','CUB','Kuba','Cuba','Havanna','CUB','Nordamerika','.cu','CUP','+53',0,0)
,('KW','','KWT','Kuwait','Kuwait','Kuwait','KUW','Asien','.kw','KWD','+965',0,0)
,('LA','','LAO','Laos','Lao People\'s Democratic Republic','Vientiane','LAO','Asien','.la','LAK','+856',0,0)
,('LS','','LSO','Lesotho','Lesotho','Maseru','LES','Afrika','.ls','LSL','+266',0,0)
,('LV','','LVA','Lettland','Latvia','R?ga','LAT','Europa','.lv','LVL','+371',1,0)
,('LB','','LBN','Libanon','Lebanon','Beirut','LIB','Asien','.lb','LBP','+961',0,0)
,('LR','','LBR','Liberia, Republik','Liberia','Monrovia','LBR','Afrika','.lr','LRD','+231',0,0)
,('LY','','LBY','Libyen','Libyan Arab Jamahiriya','Tripolis','LBA','Afrika','.ly','LYD','+218',0,0)
,('LI','','LIE','Liechtenstein, Fürstentum','Liechtenstein','Vaduz','LIE','Europa','.li','CHF','+423',0,0)
,('LT','','LTU','Litauen','Lithuania','Wilna','LTU','Europa','.lt','LTL','+370',1,0)
,('LU','','LUX','Luxemburg','Luxembourg','Luxemburg','LUX','Europa','.lu','EUR','+352',1,0)
,('MO','','MAC','Macao','Macao','','','Asien','.mo','MOP','+853',0,0)
,('MG','','MDG','Madagaskar, Republik','Madagascar','Antananarivo','MAD','Afrika','.mg','MGA','+261',0,0)
,('MW','','MWI','Malawi, Republik','Malawi','Lilongwe','MAW','Afrika','.mw','MWK','+265',0,0)
,('MY','','MYS','Malaysia','Malaysia','Kuala Lumpur','MAS','Asien','.my','MYR','+60',0,0)
,('MV','','MDV','Malediven','Maldives','Malé','MDV','Asien','.mv','MVR','+960',0,0)
,('ML','','MLI','Mali, Republik','Mali','Bamako','MLI','Afrika','.ml','XOF','+223',0,0)
,('MT','','MLT','Malta','Malta','Valletta','MLT','Europa','.mt','EUR','+356',1,0)
,('MA','','MAR','Marokko','Morocco','Rabat','MAR','Afrika','.ma','MAD','+211',0,0)
,('MH','','MHL','Marshallinseln','Marshall Islands','Delap-Uliga-Darrit','','Australien','.mh','USD','+692',0,0)
,('MQ','','MTQ','Martinique','Martinique','Fort-de-France','','Nordamerika','.mq','EUR','+596',0,0)
,('MR','','MRT','Mauretanien','Mauritania','Nouakchott','MTN','Afrika','.mr','MRO','+222',0,0)
,('MU','','MUS','Mauritius, Republik','Mauritius','Port Louis','MRI','Afrika','.mu','MUR','+230',0,0)
,('YT','','MYT','Mayotte','Mayotte','Mamoudzou','','Afrika','.yt','EUR','+269',0,0)
,('MK','','MKD','Mazedonien','Macedonia, The Former Yugoslav Republic Of','Skopje','MKD','Europa','.mk','MKD','+389',1,0)
,('MX','','MEX','Mexiko','Mexico','Mexiko-Stadt','MEX','Nordamerika','.mx','MXN','+52',0,0)
,('FM','','FSM','Mikronesien, Föderierte Staaten von','Micronesia, Federated States Of','','FSM','Australien','.fm','USD','+691',0,0)
,('MD','','MDA','Moldawien','Moldova','Chi?in?u','MDA','Europa','.md','MDL','+373',0,0)
,('MC','','MCO','Monaco','Monaco','Monaco','MON','Europa','.mc','EUR','+377',0,0)
,('MN','','MNG','Mongolei','Mongolia','Ulaanbaatar','MGL','Asien','.mn','MNT','+976',0,0)
,('MS','','MSR','Montserrat','Montserrat','Plymouth','','Nordamerika','.ms','XCD','+1664',0,0)
,('MZ','','MOZ','Mosambik','Mozambique','Maputo','MOZ','Afrika','.mz','MZM','+258',0,0)
,('MM','','MMR','Myanmar','Myanmar','Rangun','MYA','Asien','.mm','MMK','+95',0,0)
,('NA','','NAM','Namibia, Republik','Namibia','Windhoek','NAM','Afrika','.na','ZAR','+264',0,0)
,('NR','','NRU','Nauru','Nauru','Yaren','NRU','Australien','.nr','AUD','+674',0,0)
,('NP','','NPL','Nepal','Nepal','Kathmandu','NEP','Asien','.np','NPR','+977',0,0)
,('NC','','NCL','Neukaledonien','New Caledonia','Nouméa','','Australien','.nc','XPF','+687',0,0)
,('NZ','','NZL','Neuseeland','New Zealand','Wellington','NZL','Australien','.nz','NZD','+64',0,0)
,('NT','','NTZ','Neutrale Zone','','','','Asien','.nt','','',0,0)
,('NI','','NIC','Nicaragua','Nicaragua','Managua','NCA','Nordamerika','.ni','NIO','+55',0,0)
,('NL','','NLD','Niederlande','Netherlands','Amsterdam','NED','Europa','.nl','EUR','+31',1,0)
,('AN','','ANT','Niederländische Antillen','Netherlands Antilles','Willemstad','AHO','Nordamerika','.an','ANG','+599',0,0)
,('NE','','NER','Niger','Niger','Niamey','NIG','Afrika','.ne','XOF','+227',0,0)
,('NG','','NGA','Nigeria','Nigeria','Abuja','NGR','Afrika','.ng','NGN','+234',0,0)
,('NU','','NIU','Niue','Niue','Alofi','','Australien','.nu','NZD','+683',0,0)
,('MP','','MNP','Nördliche Marianen','Northern Mariana Islands','Saipan','','Australien','.mp','USD','+1670',0,0)
,('NF','','NFK','Norfolkinsel','Norfolk Island','Kingston','','Australien','.nf','AUD','+6723',0,0)
,('NO','','NOR','Norwegen','Norway','Oslo','NOR','Europa','.no','NOK','+47',0,0)
,('OM','','OMN','Oman','Oman','Maskat','OMA','Asien','.om','OMR','+968',0,0)
,('AT','','AUT','Österreich','Austria','Wien','AUT','Europa','.at','EUR','+43',1,1)
,('PK','','PAK','Pakistan','Pakistan','Islamabad','PAK','Asien','.pk','PKR','+92',0,0)
,('PS','','PSE','Palästinensische Autonomiegebiete','Palestinian Territory, Occupied','Ramallah','PLE','Asien','.ps','','+970',0,0)
,('PW','','PLW','Palau','Palau','Melekeok','PLW','Australien','.pw','USD','+680',0,0)
,('PA','','PAN','Panama','Panama','Panama-Stadt','PAN','Südamerika','.pa','USD','+57',0,0)
,('PG','','PNG','Papua-Neuguinea','Papua New Guinea','Port Moresby','','Australien','.pg','PGK','+675',0,0)
,('PY','','PRY','Paraguay','Paraguay','Asunción','PAR','Südamerika','.py','PYG','+595',0,0)
,('PE','','PER','Peru','Peru','Lima','PER','Südamerika','.pe','PEN','+51',0,0)
,('PH','','PHL','Philippinen','Philippines','Manila','PHI','Asien','.ph','PHP','+63',0,0)
,('PN','','PCN','Pitcairninseln','Pitcairn','Adamstown','','Australien','.pn','NZD','+649',0,0)
,('PL','','POL','Polen','Poland','Warschau','POL','Europa','.pl','PLN','+48',0,0)
,('PT','','PRT','Portugal','Portugal','Lissabon','POR','Europa','.pt','EUR','+351',1,0)
,('PR','','PRI','Puerto Rico','Puerto Rico','San Juan','PUR','Nordamerika','.pr','USD','+1939',0,0)
,('RE','','REU','Réunion','RÉunion','Saint-Denis','','Afrika','.re','EUR','+262',0,0)
,('RW','','RWA','Ruanda, Republik','Rwanda','Kigali','RWA','Afrika','.rw','RWF','+250',0,0)
,('RO','','ROU','Rumänien','Romania','Bukarest','ROM','Europa','.ro','RON','+40',1,0)
,('RU','','RUS','Russische Föderation','Russian Federation','Moskau','RUS','Asien','.ru','RUB','+7',0,0)
,('SB','','SLB','Salomonen','Solomon Islands','Honiara','SOL','Australien','.sb','SBD','+677',0,0)
,('ZM','','ZMB','Sambia, Republik','Zambia','Lusaka','ZAM','Afrika','.zm','ZMK','+260',0,0)
,('WS','','WSM','Samoa','Samoa','Apia','SAM','Australien','.ws','WST','',0,0)
,('SM','','SMR','San Marino','San Marino','San Marino','SMR','Europa','.sm','EUR','+378',0,0)
,('ST','','STP','São Tomé und Príncipe','Sao Tome And Principe','São Tomé','STP','Afrika','.st','STD','+239',0,0)
,('SA','','SAU','Saudi-Arabien, Königreich','Saudi Arabia','Riad','KSA','Asien','.sa','SAR','+966',0,0)
,('SE','','SWE','Schweden','Sweden','Stockholm','SWE','Europa','.se','SEK','+46',1,0)
,('CH','','CHE','Schweiz','Switzerland','Bern','SUI','Europa','.ch','CHF','+41',0,0)
,('SN','','SEN','Senegal','Senegal','Dakar','SEN','Afrika','.sn','XOF','+221',0,0)
,('CS','','SCG','Serbien und Montenegro','Serbia','Belgrad','YUG','Europa','.cs','','+381',0,0)
,('SC','','SYC','Seychellen, Republik der','Seychelles','Victoria','SEY','Afrika','.sc','SCR','+248',0,0)
,('SL','','SLE','Sierra Leone, Republik','Sierra Leone','Freetown','SLE','Afrika','.sl','SLL','+232',0,0)
,('ZW','','ZWE','Simbabwe, Republik','Zimbabwe','Harare','ZIM','Afrika','.zw','ZWD','+263',0,0)
,('SG','','SGP','Singapur','Singapore','Singapur','SIN','Asien','.sg','SGD','+65',0,0)
,('SK','','SVK','Slowakei','Slovakia','Bratislava','SVK','Europa','.sk','SKK','+421',1,0)
,('SI','','SVN','Slowenien','Slovenia','Ljubljana','SLO','Europa','.si','SIT','+386',1,0)
,('SO','','SOM','Somalia, Demokratische Republik','Somalia','Mogadischu','SOM','Afrika','.so','SOS','+252',0,0)
,('ES','','ESP','Spanien','Spain','Madrid','ESP','Europa','.es','EUR','+34',1,0)
,('LK','','LKA','Sri Lanka','Sri Lanka','Colombo','SRI','Asien','.lk','LKR','+94',0,0)
,('KN','','KNA','St. Kitts und Nevis','Saint Kitts And Nevis','Basseterre','SKN','Nordamerika','.kn','XCD','+1869',0,0)
,('LC','','LCA','St. Lucia','Saint Lucia','Castries','LCA','Südamerika','.lc','XCD','+1758',0,0)
,('PM','','SPM','St. Pierre und Miquelon','Saint Pierre And Miquelon','Saint-Pierre','','Nordamerika','.pm','EUR','+508',0,0)
,('VC','','VCT','St. Vincent und die Grenadinen (GB)','Saint Vincent And The Grenadines','Kingstown','VIN','Südamerika','.vc','XCD','+1784',0,0)
,('ZA','','ZAF','Südafrika, Republik','South Africa','Tshwane / Pretoria','RSA','Afrika','.za','ZAR','+27',0,0)
,('SD','','SDN','Sudan','Sudan','Khartum','SUD','Afrika','.sd','SDD','+249',0,0)
,('GS','','SGS','Südgeorgien und die Südlichen Sandwichinseln','South Georgia And The South Sandwich Islands','Grytviken','','','','GBP','',0,0)
,('SR','','SUR','Suriname','Suriname','Paramaribo','SUR','Südamerika','.sr','SRD','+597',0,0)
,('SJ','','SJM','Svalbard und Jan Mayen','Svalbard And Jan Mayen','Longyearbyen','','Europa','.sj','NOK','',0,0)
,('SZ','','SWZ','Swasiland','Swaziland','Mbabane','SWZ','Afrika','.sz','SZL','+268',0,0)
,('SY','','SYR','Syrien','Syrian Arab Republic','Damaskus','SYR','Asien','.sy','SYP','+963',0,0)
,('TJ','','TJK','Tadschikistan','Tajikistan','Duschanbe','TJK','Asien','.tj','RUB','+992',0,0)
,('TW','','TWN','Taiwan','Taiwan, Province Of China','Taipeh','TPE','Asien','.tw','TWD','+886',0,0)
,('TZ','','TZA','Tansania, Vereinigte Republik','Tanzania, United Republic Of','Dodoma','TAN','Afrika','.tz','TZS','+255',0,0)
,('TH','','THA','Thailand','Thailand','Bangkok','THA','Asien','.th','THB','+66',0,0)
,('TL','','TLS','Timor-Leste, Demokratische Republik','Timor-leste','Dili','','Australien','.tl','IDR','+670',0,0)
,('TG','','TGO','Togo, Republik','Togo','Lomé','TOG','Afrika','.tg','XOF','+228',0,0)
,('TK','','TKL','Tokelau','Tokelau','-/-','','Australien','.tk','NZD','+690',0,0)
,('TO','','TON','Tonga','Tonga','Nuku’alofa','TGA','Australien','.to','TOP','+676',0,0)
,('TT','','TTO','Trinidad und Tobago','Trinidad And Tobago','Port-of-Spain','TRI','Südamerika','.tt','TTD','+1868',0,0)
,('TA','','TAA','Tristan da Cunha','','Jamestown','','Afrika','','','+290',0,0)
,('TD','','TCD','Tschad, Republik','Chad','N\'Djamena','CHA','Afrika','.td','XAF','+235',0,0)
,('CZ','','CZE','Tschechische Republik','Czech Republic','Prag','CZE','Europa','.cz','CZK','+420',1,0)
,('TN','','TUN','Tunesien','Tunisia','Tunis','TUN','Afrika','.tn','TND','+216',0,0)
,('TR','','TUR','Türkei','Turkey','Ankara','TUR','Asien','.tr','TRY','+90',1,0)
,('TM','','TKM','Turkmenistan','Turkmenistan','A?gabat','TKM','Asien','.tm','TMM','+993',0,0)
,('TC','','TCA','Turks- und Caicosinseln','Turks And Caicos Islands','Cockburn Town auf Grand Turk','','Nordamerika','.tc','USD','+1649',0,0)
,('TV','','TUV','Tuvalu','Tuvalu','Funafuti','','Australien','.tv','TVD','+688',0,0)
,('UG','','UGA','Uganda, Republik','Uganda','Kampala','UGA','Afrika','.ug','UGX','+256',0,0)
,('UA','','UKR','Ukraine','Ukraine','Kiew','UKR','Europa','.ua','UAH','+380',0,0)
,('SU','','SUN','Union der Sozialistischen Sowjetrepubliken','','Moskau','URS','','.su','','',0,0)
,('UY','','URY','Uruguay','Uruguay','Montevideo','URU','Südamerika','.uy','UYU','+598',0,0)
,('UZ','','UZB','Usbekistan','Uzbekistan','Taschkent','UZB','Asien','.uz','UZS','+998',0,0)
,('VU','','VUT','Vanuatu','Vanuatu','Port Vila','VAN','Australien','.vu','VUV','+678',0,0)
,('VA','','VAT','Vatikanstadt','Holy See (vatican City State)','Vatikanstadt','','Europa','.va','EUR','+3906',0,0)
,('VE','','VEN','Venezuela','Venezuela','Caracas','VEN','Südamerika','.ve','VEB','+58',0,0)
,('AE','','ARE','Vereinigte Arabische Emirate','United Arab Emirates','Abu Dhabi','UAE','Asien','.ae','AED','+971',0,0)
,('US','','USA','Vereinigte Staaten von Amerika','United States','Washington, D.C.','USA','Nordamerika','.us','USD','+1',0,0)
,('GB','','GBR','Großbritannien und Nordirland','United Kingdom','London','GBR','Europa','.gb','GBP','+44',1,0)
,('VN','','VNM','Vietnam','Viet Nam','Hà N?i','VIE','Asien','.vn','VND','+84',0,0)
,('WF','','WLF','Wallis und Futuna','Wallis And Futuna','Mata-Utu','','Australien','.wf','XPF','+681',0,0)
,('CX','','CXR','Weihnachtsinsel','Christmas Island','Flying Fish Cove','','Asien','.cx','AUD','',0,0)
,('BY','','BLR','Weißrussland','Belarus','Minsk','BLR','Europa','.by','BYR','+375',0,0)
,('EH','','ESH','Westsahara','Western Sahara','El Aaiún','','Afrika','.eh','MAD','',0,0)
,('CF','','CAF','Zentralafrikanische Republik','Central African Republic','Bangui','CAF','Afrika','.cf','XAF','+236',0,0)
,('CY','','CYP','Zypern, Republik','Cyprus','Nikosia','CYP','Asien','.cy','CYP','+357',0,0)
,('HU','','HUN','Ungarn','Hungary','Budapest','HUN','Europa','.hu','HUF','+36',1,0)
,('ME','','MNE','Montenegro','','Podgorica','MNE','Europa','.me','','+382',0,0)
